### PR TITLE
Version updated

### PR DESCRIPTION
**Pull request by nmarcetic**
Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Update version to current 0.6.0
### Which issue(s) does this PR fix/relate to?
N/A
### List any changes that modify/break current functionality
N/A
### Have you included tests for your changes?
N/A
### Did you document any new/modified functionality?
N/A

### CODE REVIEW

**Review by drasko — DISMISSED** [review]
LGTM

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Can you, please, sign this commit and update version of `load-test/build.sbt`?

**Comment by nmarcetic** [comment]
@dusanb94 Done

**Review by drasko — APPROVED** [review]
LGTM

**Review by drasko — APPROVED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]

**Pull request merged**
