### PR TITLE
MF-323 - Rename interface implementation files in writers

### LINKED ISSUE #323: Rename interface implementation files in writers
Rename `<database_name>.go` files to `messages.go` in all writers in order to be aligned with other services.

### PR DESCRIPTION
**Pull request by dborovcanin**
This pull request resolves #323.

Signed-off-by: Dušan Borovčanin <dusan.borovcanin@mainflux.com>

### CODE REVIEW

**Review by drasko — DISMISSED** [review]
LGTM

**Review by anovakovic01 — DISMISSED** [review]
LGTM!

**Comment by drasko** [comment]
@dusanb94 please update the branch

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Pull request merged**
