### PR TITLE
NOISSUE - Add Makefile target to clean old imgs

### PR DESCRIPTION
**Pull request by drasko**
Signed-off-by: drasko <drasko.draskovic@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Add Makefile target to clean old and ghost docker images and containers.

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### CODE REVIEW

**Review by chombium — CHANGES_REQUESTED** [review]
Thumbs up for this PR as I'm doing this manually all of the time. Silly me I could have made this pr :-/

I've played a bit with these commands on on my machine Arch Linux with
```
$ awk --version
GNU Awk 4.2.1, API: 2.0 (GNU MPFR 4.0.1, GNU MP 6.1.2)
```
the awk print commands with double $ return garbage and with single $ the ids of the containers and the images. All the awk print docs and examples also show that single $ should be used.

@drasko have you maybe made some mistake when writing the commands? Could you please check that?

We could also simplify the commands and get rid of the grep-awk combos.
`docker ps -a | grep mainflux | awk '{print $$1}' | xargs -r docker rm` would be
`docker rm $(docker ps -a -f "name=mainflux" -q)`
and
`docker images | grep mainflux | awk '{print $$3}' | xargs -r docker rmi` would be 
`docker rmi $(docker images "mainflux\/*" -q)`

for the `<none>` images as per [this](http://www.projectatomic.io/blog/2015/07/what-are-docker-none-none-images/) blogpost `docker rmi $(docker images -f "dangling=true" -q)` should do the trick, but I don't have any of the so I can test.

@drasko what do you think about this?

**Comment by drasko** [comment]
@chombium `awk` uses single `$`, but `$$` is escape sequence in Makefile - otherwise command would not be correct, as Makefile would treat this as a variable.

Regarding the commands you proposed they make sense, and I will try them and incorporate them if they produce indentical results as they are more elegant.

**Comment by drasko** [comment]
@chombium thanks for advices, looks like it's working and it should be OK now.

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Review by dborovcanin — APPROVED** [review]

**Review by manuio — APPROVED** [review]

**Pull request merged**
