### PR TITLE
MF-363 - Add compiled .proto files

### LINKED ISSUE #363: Error - undefined: RawMessage when tring to use go get github.com/mainflux/mainflux
In case when mainflux is used as a library
`go get github.com/mainflux/mainflux` fails with the message undefined: RawMessage

Rason for this are missing `protoc` generated files.
I think those files should either be generated during the build process or added to the repo.

More info on `protoc` generation in question can be found here https://mainflux.readthedocs.io/en/latest/dev-guide/

### PR DESCRIPTION
**Pull request by ghost**
This pull requests resolves #363.

This PR adds compiled `.proto` files to the repo so they are present when mainflux is used as a library (fetched by `go get`).

Signed-off-by: Sava Radoš <sava.rados@mainflux.com>

### CODE REVIEW

**Review by anovakovic01 — DISMISSED** [review]
LGTM!

**Review by drasko — CHANGES_REQUESTED** [review]
`proto` target is no longer prerequisite for the build. Please remove it from the [Makefile](https://github.com/mainflux/mainflux/blob/master/Makefile#L29)

**Comment by anovakovic01** [comment]
@drasko It's still needed for development.

**Review by dborovcanin — DISMISSED** [review]

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
