### PR TITLE
NOISSUE - A minor fix in the README file

### PR DESCRIPTION
**Pull request by vool**
Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### CODE REVIEW

**Review by manuio — APPROVED** [review]
LGTM

**Comment by dborovcanin** [comment]
Please follow the [contribution guidelines and sign off your commits](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md).

**Comment by drasko** [comment]
You mean `grammar`, not `grammer`, right ;)

**Comment by vool** [comment]
ha ha  !


> You mean `grammar`, not `grammer`, right ;)

**Comment by manuio** [comment]
@vool We can't merge your PR if you don't sign your commit as @dusanb94 explained to you.

**Comment by drasko** [comment]
@vool you need to sign-off your commits as explained here: https://github.com/mainflux/mainflux/pull/1294/checks?check_run_id=1474739541.

Otherwise this PR will be closed due to inactivity.

**Comment by drasko** [comment]
Closed due to inactivity.

**Pull request closed without merging**
