### PR TITLE
NOISSUE - Enable CoAP UDP port in docker-compose

### PR DESCRIPTION
**Pull request by caztial**
add udp instead of default tcp to the docker coap port.

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### CODE REVIEW

**Comment by nmarcetic** [comment]
@caztial LGTM! Can you please [sign your commit](https://github.com/mainflux/mainflux/pull/590/checks?check_run_id=62175428) so we can merge this? Its required due to [DCO](https://developercertificate.org/) Thanks!

**Comment by drasko** [comment]
Yep, looks good. I'll approve once DCO is in place.

**Review by nmarcetic — APPROVED** [review]

**Comment by nmarcetic** [comment]
@caztial Commit message missing `Signed off` that's why DCO is failing. Please [update your commit message](https://github.com/mainflux/mainflux/pull/590/checks?check_run_id=62798071) so we can merge.

**Comment by caztial** [comment]
I made the change from the github inline edit. since its a small change please go ahead without doc :)

**Comment by drasko** [comment]
It's not doc, it is DCO - you need to sign-off your commits so we can merge them. Please follow the instructions from the link.

**Comment by drasko** [comment]
@caztial are you signing this one, or we will refuse it and close it?

**Review by drasko — APPROVED** [review]
LGTM

**Comment by drasko** [comment]
Merged! Thanks @caztial

**Pull request merged**
