### PR TITLE
NOISSUE - Update dependencies

### PR DESCRIPTION
**Pull request by dborovcanin**
Signed-off-by: Dušan Borovčanin dusan.borovcanin@mainflux.com

### What does this do?
This pull request updates outdated dependencies.

### Which issue(s) does this PR fix/relate to?
There is no such issue.

### List any changes that modify/break current functionality
There should be no breaking changes. Dependencies that include breaking changes, such as `opcua`, are not included in this pull request.

### Have you included tests for your changes?
No.

### Did you document any new/modified functionality?
No.

### CODE REVIEW

**Review by drasko — APPROVED** [review]
LGTM

**Review by manuio — DISMISSED** [review]
LGTM

**Review by drasko — CHANGES_REQUESTED** [review]
I would wait with this one until you revert mProxy keepalive

**Review by drasko — DISMISSED** [review]
LGTM

**Review by manuio — DISMISSED** [review]
LGTM

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
