### PR TITLE
MF-1603 - Env file contains an invalid value

### LINKED ISSUE #1603: Env file contains an invalid value
**BUG REPORT**

Running `docker-compose -f docker-compose.yml up` failed.

1. What were you trying to achieve?
I'm trying to run Docker composition using `docker-compose -f docker-compose.yml up`.

2. What are the expected results?
I expect the composition to run successfully.

3. What are the received results?
Running `docker-compose -f docker-compose.yml up` failed.

Snipaste_2022-05-09_11-47-30

Snipaste_2022-05-09_11-48-10

should MF_AUTH_LOGIN_TOKEN_DURATION=10h

5. What are the steps to reproduce the issue?
Run `docker-compose -f docker-compose.yml up`.

6. In what environment did you encounter the issue?
ubuntu

8. Additional information you deem important:
N/A

### PR DESCRIPTION
**Pull request by zhang-chuanfeng**
### What does this do?
This pull request fixes the .env file.

### Which issue(s) does this PR fix/relate to?
Resolve #1603 

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
N/A

### Did you document any new/modified functionality?
N/A

### Notes

### CODE REVIEW

**Comment by dborovcanin** [comment]
Please [sign off your commits](https://github.com/mainflux/mainflux/pull/1604/checks?check_run_id=6349766259).

**Comment by manuio** [comment]
@zhang-chuanfeng Please update your branch and we can merge

**Review by manuio — APPROVED** [review]
LGTM

**Review by mteodor — APPROVED** [review]

**Comment by manuio** [comment]
Thank you @zhang-chuanfeng !

**Pull request merged**
