### PR TITLE
MF-1614 - Invalid handling of auth errors in Things service

### LINKED ISSUE #1614: Invalid handling of auth errors in Things service
**BUG REPORT**

1. What were you trying to achieve?
I wanted to make sure the policies mechanism added on `mainflux/0.13.0` didn't break anything on our project. So while checking the `Things Api` I could check some strange behavior when trying to fetch `Things` that doesn't exist or the `User` doesn't have access to them. My test was quite simple, I just created a random `User` and tried to fetch a `Thing ID` that doesn't exist.

3. What are the expected results?
`404 Not Found` same as `mainflux/0.12.1`

4. What are the received results?
`500 Internal Server Error`

5. What are the steps to reproduce the issue?
```sh
curl -s -X POST -H "Content-Type: application/json" http://localhost:8180/users -d '{"email":"hoge@mail.com","password":"12345678"}'
TOKEN=$(curl -s -X POST -H "Content-Type: application/json" http://localhost:8180/tokens -d '{"email":"hoge@mail.com","password":"12345678"}' | jq -r ".token")
curl -s -X GET -H "Content-Type: application/json" -H "Authorization: Bearer $TOKEN" http://localhost:8182/things/123
```

6. In what environment did you encounter the issue?
`mainflux/0.13.0`

7. Additional information you deem important:
Same thing happens when I have a `Thing` but I don't have the `read` policies on `Keto` to access it. It also throws a `500 Internal Server Error` instead of `403 Forbidden` as the [documentation](https://docs.mainflux.io/authorization/) states.

### PR DESCRIPTION
**Pull request by dborovcanin**
Signed-off-by: dusanb94 <dusan.borovcanin@mainflux.com>

### What does this do?
This pull request fixes error handling in the Things service in case of errors received during authentication or authorization.

### Which issue(s) does this PR fix/relate to?
This pull request fixes #1614.

### List any changes that modify/break current functionality
There are changes in API that now match documentation.

### Have you included tests for your changes?
Yes, tests are modified to match the service behavior.

### Did you document any new/modified functionality?
Yes.

### Notes
N/A

### CODE REVIEW

**Comment by manuio** [comment]
@dusanb94 CI is failling `hings/api/things/http/endpoint_test.go:56:2: unauthzRes is unused `

**Review by manuio — DISMISSED** [review]
LGTM

**Review by manuio — APPROVED** [review]
LGTM

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
