### PR TITLE
NOISSUE - Use mainflux prefix for NginX certs

### PR DESCRIPTION
**Pull request by drasko**
`dhparam.pem` should be prefixed with `mainflux-`,
as are other certs in prder to avoid collisions
when copying them to a local system.

Signed-off-by: drasko <drasko.draskovic@gmail.com>

### CODE REVIEW

**Review by anovakovic01 — CHANGES_REQUESTED** [review]
This will break `k8s` setup, so change and test `k8s` setup also, or lets do this some other time.

**Review by dborovcanin — COMMENTED** [review]
Please be careful here. Does this affect docker-compose and k8s setup (since nginx.conf is shared)? Should we rename `/docker/ssl/dhparam.pem` accordingly?

**Comment by drasko** [comment]
Indeed, this is touchy. I tried to setup NginX on my laptop and make it pick up local conf with `-c`, then started copying over files and wanted to facilitate this copying of certs by prefixing them with `mainflux-`.

I have corrected all occurrences of `dhparam`, but I would not like to break something :).

**Comment by drasko** [comment]
Dropping this one for now, due unnecessary potential danger (and extreme low priority).

**Pull request closed without merging**
