### PR TITLE
MF-846-Includes python as it is required for  mqtt/aedes/Dockerfile to work

### PR DESCRIPTION
**Pull request by tdestro**
make docker_mqtt requires the use of python

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Includes python as it is required for  mqtt/aedes/Dockerfile to work
Removes it when it is no longer required.

### Which issue(s) does this PR fix/relate to?
https://github.com/mainflux/mainflux/issues/846

### CODE REVIEW

**Review by drasko — APPROVED** [review]
LGTM

**Comment by drasko** [comment]
From what I saw, mqtt docker build works, just that node emits warnings. But yes, if `gyp` is used, then Python is needed.

@nmarcetic can you please check this build and review thie PR.

**Comment by nmarcetic** [comment]
@tdestro Thank you for your contribution! Really appreciate. I tested your PR, it fixes gypo build error but have a really big impact on image size, which is really important. It adds additional ~230MB to image size which is ~480MB in total, so I would suggest you consider multi-stage builds and use [recommender node-gyp alpine dep's installation](https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#node-gyp-alpine)
Here is an example of a working multi-stage build which reduces image size back to ~200mb 
```
FROM node:10.15.1-alpine as builder

## Install build toolchain, install node deps and compile native add-ons
RUN apk add --no-cache python make g++
COPY mqtt/aedes/package.json .
RUN npm rebuild && npm install --only=production

FROM node:10.15.1-alpine as app
## Copy built node modules and binaries without including the toolchain
COPY --from=builder node_modules .
COPY *.proto mqtt/* ./

EXPOSE 1883 8880

CMD ["node", "mqtt.js"]

```

Keep in mind that we have docker multi-arch so there is a [ARM Dockerfile](https://github.com/mainflux/mainflux/blob/master/mqtt/aedes/Dockerfile.arm) also, which needs to be changed and tested.

**Comment by drasko** [comment]
@tdestro why closing this one? Just make changes and push on the same branch

**Comment by tdestro** [comment]
@drasko I don't have the bandwidth to get to this and have other pressing matters. Sorry, I will look into doing it your way when I have time.

**Comment by nmarcetic** [comment]
@tdestro I did everything for you :) With respect to your PR, I made changes, test it, etc... You just need to replace with my example ^ and that's it. Really appreciate your contribution and I am sorry if my suggestion made you frustrated, I am just doing best for the project. Thank you!

**Comment by drasko** [comment]
@tdestro one does not simply open PR and close it after reviewers work. Someone had to put a work into your contribution, please respect this.

**Pull request closed without merging**
