### PR TITLE
NOISSUE - Fix MQTT Forwarder client id

### PR DESCRIPTION
**Pull request by dborovcanin**
Don't set client ID for MQTT client in MQTT forwarder. It results in
error in case of multiple instances of the MQTT adapter because they all
share MQTT client ID, which makes broker disconnect all the other
adapters.

Signed-off-by: dusanb94 <dusan.borovcanin@mainflux.com>

### What does this do?
This pull request fixes shared MQTT client id between MQTT adapter instances.

### Which issue(s) does this PR fix/relate to?
There is no such issue.

### List any changes that modify/break current functionality
MQTT adapter wasn't scaling properly because the internal MQTT client used for forwarding NATS messages used to have a fixed client ID, which was shared between instances. This results in only one MQTT forwarder being subscribed at the time.

### Have you included tests for your changes?
No.

### Did you document any new/modified functionality?
No.

### CODE REVIEW

**Review by blokovi — DISMISSED** [review]

**Review by blokovi — DISMISSED** [review]

**Comment by nmarcetic** [comment]
@dusanb94 It's not really important to know ID while you debugging messaging on the MQTT side (so you know it's a forwarder, not an actual client/thing)?  If so, maybe it's better to stick rand Int on `mqtt-publisher-%rand`?

**Review by manuio — DISMISSED** [review]
LGTM

**Comment by dborovcanin** [comment]
> @dusanb94 It's not really important to know ID while you debugging messaging on the MQTT side (so you know it's a forwarder, not an actual client/thing)? If so, maybe it's better to stick rand Int on `mqtt-publisher-%rand`?

@nmarcetic Good catch. I'd rather let the broker generate an id, but  I added a username that can be used to differentiate MQTT publishers and clients.

**Comment by nmarcetic** [comment]
@dusanb94 Make sense.

**Review by nmarcetic — APPROVED** [review]

**Review by blokovi — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
