### PR TITLE
NOISSUE - Use .env vars in docker-compose

### PR DESCRIPTION
**Pull request by manuio**
Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

### CODE REVIEW

**Review by anovakovic01 — DISMISSED** [review]
LGTM!

**Review by mteodor — DISMISSED** [review]
LGTM

**Comment by nmarcetic** [comment]
@manuio There is a `.env` already in `docker/` can you move everything there or pull everything out?

**Review by drasko — DISMISSED** [review]
LGTM

**Review by anovakovic01 — DISMISSED** [review]
LGTM!

**Review by nmarcetic — DISMISSED** [review]

**Review by blokovi — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Pull request merged**
