### PR TITLE
NOISSUE - Expose SenML subject from Normalizer service

### PR DESCRIPTION
**Pull request by dborovcanin**
Signed-off-by: Dušan Borovčanin <dusan.borovcanin@mainflux.com>

### CODE REVIEW

**Review by anovakovic01 — COMMENTED** [review]
Why do we need this?

**Comment by drasko** [comment]
@anovakovic01 Dusan is trying to avoid duplicating strings and keeping them only in one place.

This is no necessary, because we have string only on 2 places for now, but I do not think that it is bad.

**Review by anovakovic01 — COMMENTED** [review]
@drasko Thanks for explanation. I don't think that it is bad, I just wanted to know purpose of this change. @dusanb94 Maybe we should move this constant to project root? That way, we avoid writer being directly dependent on normalizer (import of normalizer is dependency).

**Comment by drasko** [comment]
@anovakovic01 @dusanb94 yes - moving the libs/code that is shared between several components to the root dir is a good idea.

Note specially that in some scenarios `writer`s will be used (probably after some modifications) without `normalizer` - where `SenML` is not used, but some other custom message format.

**Comment by drasko** [comment]
Additionally, separate file in the project root that will hold all topics (NATS subjects) used in the system with proper comments would be a great source of documentation.

**Review by drasko — CHANGES_REQUESTED** [review]
PLease move topic information to the file in the project root.

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
