### PR TITLE
MF-838 - Migration to Go Module

### LINKED ISSUE #838: Migration to Go Module
**FEATURE REQUEST**

Switch to Go module makes the code more compatible with Go environment and standard.

### PR DESCRIPTION
**Pull request by anovakovic01**
### What does this do?
Migrates mainflux project from dep to go modules.

### Which issue(s) does this PR fix/relate to?
Resolves #838.

### List any changes that modify/break current functionality
There are no such changes

### Have you included tests for your changes?
No. I've tested existing services manually.

### Did you document any new/modified functionality?
I've updated the existing documentation.

### CODE REVIEW

**Review by manuio — DISMISSED** [review]
LGTM

**Review by dborovcanin — DISMISSED** [review]

**Review by nmarcetic — DISMISSED** [review]

**Review by drasko — CHANGES_REQUESTED** [review]
Please compare with https://github.com/mainflux/mainflux/pull/840/files - looks like there are more README files where docs should be corrected (in adapters for eample).

**Comment by anovakovic01** [comment]
@drasko it looks to me like documentation is redundant. I've updated it in the official doc. This how-to clone Mainflux part should be removed from README files.

**Comment by drasko** [comment]
Agreed, but then please go on and remove it as a part of this PR to remove potential discrepancies in the doc.

**Comment by anovakovic01** [comment]
@drasko I've already updated README files.

**Review by drasko — APPROVED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]

**Pull request merged**
