### PR TITLE
NOISSUE - Add info default value to log levels

### PR DESCRIPTION
**Pull request by darkodraskovic**
Signed-off-by: Darko Draskovic <darko.draskovic@gmail.com>

### What does this do?

Adds default "info" log level environment variables.

### Have you included tests for your changes?

No.

### Did you document any new/modified functionality?

No need for docs.

### CODE REVIEW

**Review by chombium — CHANGES_REQUESTED** [review]
Could you please elaborate why you've set info as a default log level? Usually error is set as default log level. I guess you want to have something for dev purposes.

If we want to have the log level to be the same for all of the services and configurable, it would be better if we have another envvar. If this envvar is not set from outside the run script will set a default value.

Than you can simply overwrite the default log level with something like this:

```MF_LOG_LEVEL=info ./run.sh```

Another question is if we want to have granular setting of the log level per service, so that the users can set different log levels per service.

**Comment by drasko** [comment]
@darkodraskovic I agree with @chombium's remarks - add `MF_LOG_LEVEL=info ./run.sh` in `Makefile`.

@chombium this `make run` is running microservices natively and is for now for development purposes, this is why @darkodraskovic proposed to add some more logs useful during development stage.

I would propose that we change also `run` target into `rundev` (for development native run with logs), and use `make run` to run docker containers.

**Comment by chombium** [comment]
@drasko I understand that that's for development purposes, but even then, because of the missing flexibility to set the log level from outside, it can happen that someone changes the log levels to and unintentionally commits the changed shell script.

We could also add a new rundev.sh file to the git ignores and everyone can configure the log levels as he/she wants. That would also do the trick

**Comment by chombium** [comment]
@drasko I understand that that's for development purposes, but even then, because of the missing flexibility to set the log level from outside, it can happen that someone changes the log levels to and unintentionally commits the changed shell script.

We could also add a new rundev.sh file to the git ignores and everyone can configure the log levels as he/she wants. That would also do the trick

**Comment by chombium** [comment]
@drasko I understand that that's for development purposes, but even then, because of the missing flexibility to set the log level from outside, it can happen that someone changes the log levels to and unintentionally commits the changed shell script.

**Comment by drasko** [comment]
Closing this one, will be implemented through https://github.com/mainflux/mainflux/pull/427

**Pull request closed without merging**
