### PR TITLE
MF-786 - Add message tracing over NATS using open tracing standard

### LINKED ISSUE #786: Add message tracing over NATS using open tracing standard
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
After adding open tracing support to the existing gRPC and HTTP endpoints in `Users` and `Things` service, we should add support for tracing async messages that are sent over Mainflux.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a must-have.

### PR DESCRIPTION
**Pull request by nwneisen**
### What does this do?
Adds open tracing for NATS messages.

### Which issue(s) does this PR fix/relate to?
Resolves #786

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### CODE REVIEW

**Comment by nwneisen** [comment]
I tested to verify I saw spans generated for http and ws.  I am still working on setting up LORA and COAP and I will verify with them as well.

**Review by drasko — COMMENTED** [review]
This looks good, but I'll let @anovakovic01 and @srados approve, as they were involved more in Open Tracing then me.

However I notice that in general our package organization shoul dbe improved so we can mutualize the code, as there is a lot of repetitions for each microservice...

**Comment by nwneisen** [comment]
@drasko  Yes, I agree.  In #787, @anovakovic01 and I spoke briefly about putting the tracing code into a common location for reusability in its own PR.

**Comment by nwneisen** [comment]
I'm going to close this PR for now and I will reopen it once I've done more research and added those changes.

**Pull request closed without merging**
