### PR TITLE
Typos; readability formatting of long command; update cli command name

### PR DESCRIPTION
**Pull request by david-drinn**

### CODE REVIEW

**Review by drasko — APPROVED** [review]
LGTM

**Review by chombium — APPROVED** [review]
LGTM

**Comment by chombium** [comment]
@david-drinn please sign the commits

**Comment by drasko** [comment]
@david-drinn please sign-off your commits, or PR will be closed due to inactivity.

**Comment by nmarcetic** [comment]
@david-drinn please [sign the commits](https://help.github.com/en/articles/signing-commits) so we can merge this

**Review by manuio — APPROVED** [review]

**Review by manuio — APPROVED** [review]

**Comment by drasko** [comment]
Closing due to inactivity. Please reopen if needed.

**Pull request closed without merging**
