### PR TITLE
Happy New Year

### PR DESCRIPTION
**Pull request by dborovcanin**
:tada:

### CODE REVIEW

**Review by drasko — DISMISSED** [review]
Fuckin' approved!

Happy New Year everybody!

**Review by anovakovic01 — COMMENTED** [review]
What about license comments? :) Happy New year!

**Review by chombium — DISMISSED** [review]

**Comment by dborovcanin** [comment]
@anovakovic01 I'm not sure, I think that we should keep all the license comments untouched, but I'd like to know what @mainflux/maintainers think.

**Comment by chombium** [comment]
Nice discussions on the subject:
* [What copyright date for an update to an open-source project from last year?](https://softwareengineering.stackexchange.com/questions/130478/what-copyright-date-for-an-update-to-an-open-source-project-from-last-year)
* [Do copyright dates need to be updated?](https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated)

From what I've read, the important thing is that the copyright goes back to the moment when it was claimed for the first time and the practice is that you can update the year if you make some changes to a specific file, but it's not a must.

**Review by nmarcetic — DISMISSED** [review]

**Comment by nmarcetic** [comment]
@dusanb94 Please update branch.

**Review by drasko — APPROVED** [review]
LGTM

**Review by nmarcetic — APPROVED** [review]

**Pull request merged**
