### PR TITLE
NOISSUE - Remove UI from docker-compose

### PR DESCRIPTION
**Pull request by manuio**
Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

### CODE REVIEW

**Review by drasko — DISMISSED** [review]
LGTM

**Comment by drasko** [comment]
Approved. We should note somewhere in the documentation how UI should be run, for the people that want to run Mainflux with UI.

**Review by mteodor — DISMISSED** [review]

**Comment by nmarcetic** [comment]
@manuio Remove from `.env` also.

**Review by dborovcanin — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
