### PR TITLE
NOISSUE - Add rejected at to sdk

### PR DESCRIPTION
**Pull request by SammyOina**
# What type of PR is this?
This is a bug fix that adds rejected at to sdk struct

## What does this do?
- **New Features**
	- Introduced a new field to track the rejection timestamp of invitations, enhancing invitation management and processing capabilities.

## Have you included tests for your changes?
Yes

## Did you document any new/modified feature?
No

### CODE REVIEW

**Review by WashingtonKK — CHANGES_REQUESTED** [review]
Also update sdk http method.

**Review by WashingtonKK — APPROVED** [review]

**Review by WashingtonKK — CHANGES_REQUESTED** [review]
Update CLI too, add `rejectInvitation` to CLI

**Review by WashingtonKK — CHANGES_REQUESTED** [review]
Also add SDK tests for rejectInvitation.

**Review by WashingtonKK — DISMISSED** [review]

**Review by WashingtonKK — CHANGES_REQUESTED** [review]
Update repo function  `RetrieveAll` to include `RejectedAt`

**Comment by WashingtonKK** [comment]
> Update repo function `RetrieveAll` to include `RejectedAt`

Also do the same for `Retrieve`

**Review by dborovcanin — APPROVED** [review]

**Pull request merged**
