### PR TITLE
MF-681 - Incorrect error log in MongoDB reader test

### LINKED ISSUE #681: Incorrect error log in MongoDB reader test
**BUG REPORT**

1. What were you trying to achieve?
     Right message when run test reader-mongo error.

2. What are the expected results?
 ` err := writer.Save(msg) 
 require.Nil(t, err, fmt.Sprintf("failed to store message to MongoDB: %s", err)) 
 messages = append(messages, msg) `

## File
 https://github.com/mainflux/mainflux/blob/83cafeb6bef21d86e7ffc83a9484fbc4b02a3935/readers/mongodb/messages_test.go#L77-L79

### PR DESCRIPTION
**Pull request by nattaponra**
### What does this do?
This PR fixes log in ReadAllTest test in MongoDB reader.

### Which issue(s) does this PR fix/relate to?
This PR fixes #681.

### List any changes that modify/break current functionality
There are no such changes.

### Have you included tests for your changes?
No, this is a simple log update.

### Did you document any new/modified functionality?
No.

### CODE REVIEW

**Review by drasko — DISMISSED** [review]
LGTM

**Review by dborovcanin — DISMISSED** [review]

**Comment by drasko** [comment]
@nattaponra you need to sign off your PR in order to pass DCO. Here are the instructions: https://github.com/mainflux/mainflux/pull/682/checks?check_run_id=89125346

**Comment by nmarcetic** [comment]
@nattaponra Please sign your commits  https://github.com/mainflux/mainflux/pull/682/checks?check_run_id=90470221

**Comment by nattaponra** [comment]
> @nattaponra Please sign your commits https://github.com/mainflux/mainflux/pull/682/checks?check_run_id=90470221

Thank you for recommend
I'm trying to follow this instruction but still not pass.
Could you give me recommending or detail information about DCO? because I am never used it

**Comment by chombium** [comment]
Hi @nattaponra,

To sign a commit means that you have to add the '-s" switch to your "git commit" command.
As you haven't signed your older commits you'll have to execute something similar to:
`git filter-branch --msg-filter "cat - && echo && echo 'Signed-off-by: Your Name <Your.Name@example.com>'" HEAD~2..HEAD`

HEAD~2 means start from the head (the current revision) and go 2 commits back, as you have made 6 commits you'll have to add `HEAD~6` in your command. You can find more info about signing commits [here](https://help.github.com/en/articles/signing-commits) and [here about signing old commits](https://gist.github.com/kwk/d70f20d17b18c4f3296d).

HTH,
Jovan
P.S. You also need to update your fork. On how to do it check our [contribution guide](https://github.com/mainflux/mainflux/blame/master/CONTRIBUTING.md#L77)

**Comment by drasko** [comment]
@nattaponra please fix this PR ASAP or it will be closed due to inactivity.

**Pull request closed without merging**
