### PR TITLE
NOISSUE - Use current hostname instead of localhost for a WS connection

### PR DESCRIPTION
**Pull request by sprql**
Currently in UI WebSocket trying to connect to localhost, 
but if it used from some custom domain, it will fail.

We can use `window.location.hostname` instead of `localhost` to be able to connect even if we use a custom domain for UI.

### CODE REVIEW

**Review by blokovi — DISMISSED** [review]

**Review by drasko — DISMISSED** [review]
LGTM

**Comment by drasko** [comment]
@sprql thanks for the PR.

You need to sign-off your commits in order for PR to be accepted.

Please follow the instructions here: https://github.com/mainflux/mainflux/runs/202965395

**Review by drasko — APPROVED** [review]
LGTM

**Comment by blokovi** [comment]
LGTM, thanks @sprql

**Review by blokovi — APPROVED** [review]

**Pull request merged**
