### PR TITLE
NOISSUE - Activate Standalone Mode For Things

### PR DESCRIPTION
**Pull request by rodneyosodo**
### What does this do?
Activates standalone mode for things by setting the environment variables

### Which issue(s) does this PR fix/relate to?
Noissue

### List any changes that modify/break current functionality
Activates things to run in standalone fashion

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
Partially Linked to #1784

### CODE REVIEW

**Review by dborovcanin — APPROVED** [review]

**Review by arvindh123 — APPROVED** [review]
LGTM

**Review by arvindh123 — APPROVED** [review]

**Review by arvindh123 — APPROVED** [review]

**Review by arvindh123 — APPROVED** [review]

**Review by arvindh123 — APPROVED** [review]
LGTM

**Review by drasko — APPROVED** [review]
LGTM

**Review by drasko — APPROVED** [review]
LGTM

**Comment by rodneyosodo** [comment]
Closing this as it is already implemented on master by #1716.

**Pull request closed without merging**
