### PR TITLE
NOISSUE - Add channel ID validation

### PR DESCRIPTION
**Pull request by anovakovic01**
Add channel id validation and remove unnecessary error. Update
swagger doc accordingly.

Signed-off-by: Aleksandar Novakovic <anovakovic01@gmail.com>

### CODE REVIEW

**Review by mijicd — APPROVED** [review]

**Review by drasko — COMMENTED** [review]
To me "Not Found" would say - I searched ID in the DB and it is not present.

As I see here the case is that path is malformed, so I would maybe rather return 400 Bad Request, or something like this.

**Comment by anovakovic01** [comment]
@drasko I followed manager's API logic.

**Comment by chombium** [comment]
I agree with @drasko. Maybe we should improve this. If the id is invalid we should return bad request and if the id is valid but not found than not found.

On the other hand, if we don't want to introduce complex validation, invalid ids won't be found, so not found as a response code is also ok.

**Comment by mijicd** [comment]
@chombium it is somewhat irrelevant. Neither response would be *wrong*, but 404 is more accurate one - a resource with non UUID identifier does not exist.

**Pull request merged**
