### PR TITLE
MF-583 - Correct cmd/mongodb-reader HTTPServer log Info

### LINKED ISSUE #583: Correct cmd/mongodb-reader HTTPServer log Info
[cmd/mongodb-reader/mian.go@master#L170](https://github.com/mainflux/mainflux/blob/94574e3707479a4364b965fd26901ce7f604bd17/cmd/mongodb-reader/main.go#L170) startHTTPServer log info shows`cassandra-reader` should be typo error

It should be correct to `mongodb-reader`

### PR DESCRIPTION
**Pull request by cage1016**
### What does this do?

correct `cmd/moanog-reader` HTTPServer log info typo error 

### Which issue(s) does this PR fix/relate to?

This PR resolves #583 

### List any changes that modify/break current functionality

There are no such changes

### Have you included tests for your changes?

N/A

### Did you document any new/modified functionality?

There are no such changes

### Notes

just fix typo error

### CODE REVIEW

**Review by anovakovic01 — DISMISSED** [review]
LGTM!

**Review by dborovcanin — DISMISSED** [review]

**Comment by nmarcetic** [comment]
@cage1016 Thank you for this fix. Everything looks OK, please [sign your commit](https://github.com/mainflux/mainflux/pull/584/checks?check_run_id=61426968) and update branch, so we can merge it. Thanks!

**Review by drasko — DISMISSED** [review]
LGTM

**Review by nmarcetic — APPROVED** [review]

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Comment by nmarcetic** [comment]
Thanks, @cage1016

**Pull request merged**
