### PR TITLE
MF-1263 - Move repeating errors to the separate package

### LINKED ISSUE #1263: Move repeating errors to the separate package
**FEATURE REQUEST**

1. Is there an open issue addressing this request?
No.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.
Consider moving errors that repeat such as Unauthorized, MalformedEntity, and Conflict to the `errors ` package so that we have it in one place, instead of repeating the code for each service.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).
This is a nice-to-have.

_Originally posted by @mteodor in https://github.com/mainflux/mainflux/pull/1262#discussion_r510772637_

### PR DESCRIPTION
**Pull request by manuio**
Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

Resolves #1263

### CODE REVIEW

**Review by drasko — COMMENTED** [review]
I think unification of errors would be a great simplification in our case, as we have many repeating error definitions in various packages (services).

Never the less, I would like to hear opinions of other maintainers - @dusanb94 @manuio @nmarcetic  - does this looks OK to you.

I am very close to approve this one.

**Comment by manuio** [comment]
@drasko Yes, it looks OK to me

**Review by mteodor — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]

**Review by blokovi — APPROVED** [review]

**Comment by manuio** [comment]
@drasko Should I merge this one?

**Comment by drasko** [comment]
@manuio just a sec, I want to look at this again. Will be merged soon.

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
