### PR TITLE
MF-1020 - Change default password for CLI provision test

### LINKED ISSUE #1020: CLI provision test not work with the UI
**BUG REPORT**

1. What were you trying to achieve?
The command to provision the system for testing is not compatible

2. What are the expected results?
The generate account must be usable with the UI.

3. What are the received results?
The default password is not allowed by the UI (not enough length).

4. What are the steps to reproduce the issue?
Running a cleaned docker-compose with the container linked.

5. In what environment did you encounter the issue?
In docker container

6. Additional information you deem important:
Maybe, it is good idea a generate a random password.

### PR DESCRIPTION
**Pull request by jonathandreyer**
### What does this do?
Change the default password for CLI provision test.

### Which issue(s) does this PR fix/relate to?
Resolves #1020.

### List any changes that modify/break current functionality
NA

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes
NA

### CODE REVIEW

**Review by manuio — APPROVED** [review]
LGTM

**Comment by drasko** [comment]
@manuio @nmarcetic why is UI password limited to 6 chars? Why not 8+, as it is a [usual practice](https://en.wikipedia.org/wiki/Password_strength#Common_guidelines)?

**Comment by nmarcetic** [comment]
> @manuio @nmarcetic why is UI password limited to 6 chars? Why not 8+, as it is a [usual practice](https://en.wikipedia.org/wiki/Password_strength#Common_guidelines)?

@drasko I dunno about UI.  I am not sure that we are checking len neither on the API side.

**Review by nmarcetic — APPROVED** [review]

**Comment by nmarcetic** [comment]
Thanks @jonathandreyer

**Comment by drasko** [comment]
@nmarcetic I do not think that this w smart. You have now forced a test password to 6 chars, without particular reason, and you are propagating the error of having 6 chars in the first place into our CLI.

I do not care about UI, but I do if you pollute the core.

**Pull request merged**
