### PR TITLE
MF-325 - Add SPDX license and copyright headers

### LINKED ISSUE #325: Add SPDX license and copyright headers
Following the good practices for professional open-source projects, all Mainflux files should have proper license and copyright headers.

SPDX standard should be used to prevent code bloating: https://spdx.org/licenses/

### PR DESCRIPTION
**Pull request by blokovi**
This pull request resolves #325.

### CODE REVIEW

**Review by drasko — DISMISSED** [review]
LGTM

**Review by dborovcanin — DISMISSED** [review]

**Review by anovakovic01 — CHANGES_REQUESTED** [review]
Add this to `.proto` and `.css` files as well.

**Comment by drasko** [comment]
@blokovi looks good, please add Scala files as well.

**Review by anovakovic01 — DISMISSED** [review]
LGTM!

**Review by drasko — DISMISSED** [review]
LGTM

**Comment by drasko** [comment]
@blokovi please resolve conflicts and update branch.

**Review by drasko — APPROVED** [review]

**Review by nmarcetic — APPROVED** [review]

**Comment by drasko** [comment]
Merged! Thanks @blokovi

**Pull request merged**
