### PR TITLE
MF-785 - Change CanAccess to CanAccessByKey

### LINKED ISSUE #785: Rename CanAccess endpoint to CanAccessByKey
Currently, `things` service has two gRPC endpoints that are very similar. The first one is called `CanAccess` while the second one is called `CanAccessByID`. The first one should be renamed to `CanAccessByKey` in order to be consistent.

### PR DESCRIPTION
**Pull request by nwneisen**
### What does this do?
Change `CanAccess` code to use `CanAccessByKey`

### Which issue(s) does this PR fix/relate to?
Resolves #785 

### List any changes that modify/break current functionality
Endpoint `/channels/<channel id>/access` was changed to `/channels/<channel id>/access-by-key`.  This could cause issues if it was being access outside of the SDK.  It didn't seem to be exposed.

### Have you included tests for your changes?
No new tests were created.  Current tests were verified to still be passing.

### Did you document any new/modified functionality?
No, new functionality was not added and this endpoint is not documented.

### CODE REVIEW

**Comment by drasko** [comment]
@nwneisen great initiative.

However this change will probably impact Aedes and VerneMQ MQTT adapters, as they depend on protobuf (which was changed).

Can you please verify if this is the case, and do the necessary changes over there as well (at least for Aedes, and I can do Erlang stuff for VerneMQ later).

**Comment by drasko** [comment]
@dusanb94 these seem to be commited.

Also I double-checked that Verne does not use `CanAccessByKey()` (it uses only `CanAccessByID()`, which was the reason for introducing it and making these distinctions).

However, I think that Aedes [calls](https://github.com/mainflux/mainflux/blob/master/mqtt/aedes/mqtt.js#L229) need to be adjusted.

**Comment by drasko** [comment]
On double-checking PR Aedes code seems to be handled as well.

I have good impression about this PR ;).

**Review by nmarcetic — DISMISSED** [review]

**Review by drasko — DISMISSED** [review]
LGTM

**Comment by drasko** [comment]
@nwneisen I tried updating your branch via GitHUb UI button (as you have maintainer approvals, and we would like to merge this PR). However, CI is falling - probably because wrong protoc version.

Can you try updating the branch manually to see if we can fix this issue?

Our CI script seems to use [this version](https://github.com/mainflux/mainflux/blob/master/scripts/ci.sh#L32) of `protoc`. We should either bump it, remove this check, or you must for now align with what CI does.

@dusanb94 can we take a look at bumping this `protoc` version, looks like [3.10](https://github.com/protocolbuffers/protobuf/releases) is actual one.

**Comment by nwneisen** [comment]
@drasko I checked my protoc version and I was indeed on 3.9.1.  It looks like the build is now successful and I just needed to push with a signed commit.

**Review by drasko — APPROVED** [review]
LGTM

**Review by manuio — APPROVED** [review]
LGTM

**Comment by drasko** [comment]
Merged! Thanks @nwneisen!

**Pull request merged**
