### PR TITLE
NOISSUE - Remove Elm UI

### PR DESCRIPTION
**Pull request by manuio**
Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

### CODE REVIEW

**Review by blokovi — APPROVED** [review]

**Comment by blokovi** [comment]
You can remove `MF_UI_PORT` from `.env` file also

**Comment by blokovi** [comment]
> You can remove `MF_UI_PORT` from `.env` file also

Or maybe not because it's in nginx configuration

**Comment by manuio** [comment]
@blokovi yes, you need it here: https://github.com/mainflux/mainflux/blob/master/docker/docker-compose.yml#L234

**Review by dborovcanin — APPROVED** [review]

**Comment by chombium** [comment]
@manuio @blokovi we should remove the `MF_UI_PORT` and when someone wants to deploy the ui as well, he/she can use the docker-compose overriding as described [here](https://github.com/mainflux/mainflux/blob/master/docs/dev-guide.md#overriding-the-default-docker-compose-configuration). We should add a new docker-compose file with the [ui comfig](https://github.com/mainflux/mainflux/blob/master/docker/docker-compose.yml#L229-L238) in a docker-compose.yml file.

As adding the configuration for the ui is out of scope for this issue I suggest that we merge this and open another issue

**Comment by drasko** [comment]
@chombium UI will not be removed, but basic Elm UI replaced with new one that @manuio made with [ngx-admin](https://github.com/akveo/ngx-admin) and will be placed here: https://github.com/mainflux/ui

**Comment by drasko** [comment]
For the reference, Elm UI has been moved [here](https://github.com/MainfluxLabs/ui-elm).

**Comment by chombium** [comment]
@drasko thanks for the clarification.
I saw that the Elm UI has been moved as it was previously discussed, but I didn't know that there is a new UI.

**Pull request merged**
