### PR TITLE
NOISSUE - Switch to grpcbox for VerneMQ

### PR DESCRIPTION
**Pull request by drasko**
Use grpcbox as a gRPC client library, because
it is much better maintained.

Shows good performance and generation of protobuf
files is simple and automatic.

Signed-off-by: Drasko DRASKOVIC <drasko.draskovic@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### CODE REVIEW

**Review by manuio — DISMISSED** [review]
LGTM

**Review by anovakovic01 — DISMISSED** [review]
LGTM!

**Review by manuio — DISMISSED** [review]
LGTM

**Comment by drasko** [comment]
Although stable, this implementation shows less performance than the current master. I will close PR, we'll have this branch as a reference if something is needed.

**Review by dborovcanin — DISMISSED** [review]

**Pull request merged**
