### PR TITLE
NOISSUE - Clean NginX files, move .gitignores to dirs

### PR DESCRIPTION
**Pull request by drasko**
Signed-off-by: drasko <drasko.draskovic@gmail.com>

Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](./CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Small cleanings, NginX entrypoint was leaving debug trash behind.

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)

### CODE REVIEW

**Review by nmarcetic — COMMENTED** [review]
I don't see .gitignore for Aedes, node_modules etc...?

**Comment by drasko** [comment]
> I don't see .gitignore for Aedes, node_modules etc...?

It has only `node_modules`, and by convention these go to private global `.gitignore`, mentioned [here](https://github.com/mainflux/mainflux/pull/853/commits/cfbb898f8c746c1c95ca2b0174267e3066d21d92#diff-a084b794bc0759e7a6b77810e01874f2R5).

**Comment by nmarcetic** [comment]
@drasko Its not the same. `node_modules` are generated by the project and this ref link is just recommendation like good idea, not convention. Please revert back .gitignore for MQTT Aedes adapter and add node_modules there.

**Comment by drasko** [comment]
@nmarcetic makes sense. Will do so.

**Comment by drasko** [comment]
@nmarcetic updated.

**Review by anovakovic01 — DISMISSED** [review]
LGTM!

**Review by dborovcanin — DISMISSED** [review]

**Review by dborovcanin — APPROVED** [review]

**Review by nmarcetic — APPROVED** [review]

**Pull request merged**
