### PR TITLE
README minor typos - "continuously"

### PR DESCRIPTION
**Pull request by david-drinn**

### CODE REVIEW

**Review by drasko — APPROVED** [review]
LGTM

**Review by chombium — APPROVED** [review]

**Comment by chombium** [comment]
@david-drinn please sign the commits

**Comment by drasko** [comment]
@david-drinn please sign-off your commits, or PR will be closed due to inactivity.

**Comment by nmarcetic** [comment]
@david-drinn please [sign the commits](https://help.github.com/en/articles/signing-commits) so we can merge this

**Comment by david-drinn** [comment]
Ok working on signing.

**Comment by drasko** [comment]
Closed due to inactivity. Please reopen if needed.

**Pull request closed without merging**
