### PR TITLE
MF-443 Update project dependencies

### LINKED ISSUE #425: Update grpc-go libraries to latest versions
**BUG REPORT**
Ran into this bug, and it seems that it's fixed in 12.1: https://github.com/grpc/grpc-go/pull/2045

1. What were you trying to achieve?
Run with nginx using grpc load balancing
2. What are the expected results?
success
3. What are the received results?
`2018/10/23 15:29:06 [error] 30157#30157: *5357193 upstream sent invalid header while reading response header from upstream, client: 127.0.0.1, server: things-grpc, request: "POST /mainflux.ThingsService/CanAccess HTTP/2.0", upstream: "grpc://10.0.0.1:8181", host: "things-grpc:443"`
4. What are the steps to reproduce the issue?
- nginx 1.15.3 deployed as ingress controller
- things-grpc ingress annotated with backend protocol as `GRPC`
- attempt to publish message 
- error occurs occasionally
5. In what environment did you encounter the issue?
Kubernetes-deployed using nginx 1.15.3 with grpc as backend protocol connecting to things.
6. Additional information you deem important:

### LINKED ISSUE #443: Update project dependencies
Project dependencies need update. A lot of dependencies use an obsolete version and we should update them for potential bug fixes or other improvements. Good example is known issue #425.

### PR DESCRIPTION
**Pull request by dborovcanin**
### What does this do?
This pull request updates project dependencies.

### Which issue(s) does this PR fix/relate to?
 This pull request closes #443 and fixes #425.

### List any changes that modify/break current functionality
There shouldn't be breaking changes here. Only minor/patch version of dependencies is updated, so everything should be backward compatible.

### CODE REVIEW

**Review by drasko — DISMISSED** [review]
LGTM

**Comment by drasko** [comment]
@dusanb94 needs update.

**Review by drasko — APPROVED** [review]
LGTM

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Pull request merged**
