### PR TITLE
NOISSUE - Rename MQTT port variable for docker environment

### PR DESCRIPTION
**Pull request by blokovi**
Signed-off-by: Ivan Milošević <iva@blokovi.com>

Align name of variable with [mqtt/main.go](https://github.com/mainflux/mainflux/blob/master/cmd/mqtt/main.go#L45)

### CODE REVIEW

**Review by nmarcetic — COMMENTED** [review]
Please don't forget to rename vars in the helm chart also.

**Review by nmarcetic — APPROVED** [review]

**Comment by blokovi** [comment]
> Please don't forget to rename vars in the helm chart also.



In fact, there was already good var name, in docker is wrong

**Review by manuio — APPROVED** [review]
LGTM

**Review by drasko — APPROVED** [review]
LGTM

**Pull request merged**
