### PR TITLE
MF-1670 - Improve error handling in SDK

### LINKED ISSUE #1670: Improve error handling in SDK
**FEATURE REQUEST**

1. Is there an open issue addressing this request? If it does, please add a "+1" reaction to the
   existing issue, otherwise proceed to step 2.

There is no such issue.

2. Describe the feature you are requesting, as well as the possible use case(s) for it.

Currently, our SDK returns a generic error and status code of the response that caused it, not taking into account **what's the actual error return by the underlying service**. For example, when updating Thing or Channel, we return something like:
`failed to update: status 400`. This tells the end-user - exactly nothing. First, if `sdk.Update` returns an error - it's obviously _failed to update_, so that returned error that says it's failed update tells nothing. Second, status code 400 can be caused by so many things on the backend since one status code can be bound with an enormous amount of errors.
To fix this, we should update SDK so it uses the response body to read the error message service returned and remove useless generic errors such as _failed to update_.

3. Indicate the importance of this feature to you (must-have, should-have, nice-to-have).

This is a must-have because proper SDK error handling is extremely important in some cases, such as here #1669.

### PR DESCRIPTION
**Pull request by dborovcanin**
Signed-off-by: dusanb94 <dusan.borovcanin@mainflux.com>

### What does this do?
This pull request fixes error handling on the Maifnlux SDK.

### Which issue(s) does this PR fix/relate to?
This pull request resolves #1670.

### List any changes that modify/break current functionality
Errors returned by SDK are changed to include server errors for the respective request. 

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
N/A

### Notes
N/A

### CODE REVIEW

**Comment by arvindh123** [comment]
Please add status code to errors.
To find the error exact, we need combination of status code and response body, because of error encoding ```(encodeError)``` in ```MakeHandler```  ,

**Comment by dborovcanin** [comment]
> Please add status code to errors. To find the error exact, we need a combination of status code and response body, because of error encoding `(encodeError)` in `MakeHandler` ,

Makes sense. Since SDK is made for developers, including the status code to an error makes sense so the user can precisely determine what exactly happened. We could put a status code to the error message - but that would make things only more complex and this kind of transparency in SDK makes it harder to use. We can create separate errors (that implement our Error interface, ofc) for SDK and include the status code there. Also, potentially in the future, an error response will include more than `{"error": "message"}` JSON, so we'll need even more complex handling on the SDK which would also justify adding a new, SDK error. @drasko What do you think?

**Comment by drasko** [comment]
I think this makes sense completely. I like the idea of evolved `error` structure.

**Comment by dborovcanin** [comment]
Closing as a duplicate of #1674.

**Pull request closed without merging**
