### PR TITLE
Fix nginx config issue

### PR DESCRIPTION
**Pull request by Maxpeng92**
#179 Fix Nginx config issue.

### CODE REVIEW

**Review by mijicd — APPROVED** [review]

**Comment by nmarcetic** [comment]
@Maxpeng92 You have a same `/` [here](https://github.com/Maxpeng92/mainflux/blob/1577e997a8111b49e30ff2c46bf2c597fc4cf9da/docker/nginx.conf#L135) Also you didn't remove network_mode as you mention 
`If you don't create virtual network by commenting out network_mode`

I[ requested a  changes on PR](https://github.com/mainflux/mainflux/pull/181#pullrequestreview-103889213)

Did you test composition before sending PR ? Is it working ?

**Review by nmarcetic — CHANGES_REQUESTED** [review]
You have a same / at the end of `proxy_pass` to docker-manger. Also you didn't remove network_mode as you mention
If you don't create virtual network by commenting out network_mode

**Comment by drasko** [comment]
Why is Semaphore failing here and I also can not see DCO check

**Comment by Maxpeng92** [comment]
@nmarcetic You only need to make sure not have a "/" when you use regex in Nginx config, that's why I only change line 152. Also, I mentioned I will let docker-compose file as what it was because you guys properly want to switch to docker swarm that's why I didn't comment out network_mode. 

PS: It's working by only changing line 152. Comment out network_mode won't fully fix the issue. You need to start the failed starting containers individually if there is any.

**Comment by mijicd** [comment]
@Maxpeng92 please include the change into #185. These are "one liners" and are closely related, there is no point having 2 PRs for that.

**Comment by Maxpeng92** [comment]
@mijicd Sure. I did.

**Pull request closed without merging**
