### PR TITLE
NOISSUE - Set To MF_USERS_GRPC_ Var to Docker-Compose

### PR DESCRIPTION
**Pull request by rodneyosodo**
### What does this do?
Sets `MF_USERS_GRPC_` to the `MF_AUTH_GRPC_` variable in docker-compose file and README docs

### Which issue(s) does this PR fix/relate to?
Noissue

### List any changes that modify/break current functionality
Env vars

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
Yes

### Notes
N/A

### CODE REVIEW

**Review by dborovcanin — COMMENTED** [review]
Let's think about this one because Users act like Auth providers so this change might not be necessary.

**Comment by SammyOina** [comment]
exclude merge commits

**Comment by rodneyosodo** [comment]
> Let's think about this one because Users act like Auth providers so this change might not be necessary.

Repurposing this so that we have `MF_AUTH_` set as an environment variable

**Comment by rodneyosodo** [comment]
CI is fixed by [`6e919ba` (#1781)](https://github.com/mainflux/mainflux/pull/1781/commits/6e919ba872434c328af544e22410687ea0a11490)

**Review by dborovcanin — APPROVED** [review]

**Pull request merged**
