### PR TITLE
MF-1059 - Add TLS support for email

### LINKED ISSUE #1059: Add TLS support for email
When password reset request is issued email is sent to the user.
Currently it only works with unsecure smtp.

### PR DESCRIPTION
**Pull request by blokovi**
### What does this do?
Use gomail package for sending emails

### Which issue(s) does this PR fix/relate to?
Resolves #1059

### CODE REVIEW

**Review by manuio — DISMISSED** [review]
LGTM

**Comment by manuio** [comment]
@blokovi Looks like vendor wasn't updated properly.

**Comment by blokovi** [comment]
> @blokovi Looks like vendor wasn't updated properly.

@manuio I forgot to add vendor, thanks.

**Review by manuio — DISMISSED** [review]
LGTM

**Review by manuio — APPROVED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]

**Pull request merged**
