### PR TITLE
NOISSUE - Add exported metrics visualization for grafana

### PR DESCRIPTION
**Pull request by anovakovic01**
Add graphs for request count and request latency for users, things,
http adapter and ws adapter services.

Signed-off-by: Aleksandar Novakovic <aleksandar.novakovic@mainflux.com>

### CODE REVIEW

**Review by drasko — COMMENTED** [review]
maybe `dashboar-metrics.json` should be renamed into `grafana-metrics.json` so that people know what is it for (because it sits in the project root)?

**Review by nmarcetic — CHANGES_REQUESTED** [review]
I don't like idea to put this in project root. Is there any special reason for this or its a personal choice ?

**Review by nmarcetic — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM

**Comment by drasko** [comment]
@anovakovic01 please update the branch, so we can merge.

**Review by dborovcanin — APPROVED** [review]

**Pull request merged**
